version: '3.3'

networks:
  overlay:

services:
  web:
    restart: always
    build: ./php-apache
    ports:
      - "80:80"
    networks:
      - overlay
    volumes:
      - ./project:/var/www/
      - ./apache:/etc/apache2/sites-available/

  postgres:
    image: "postgres:14.1-alpine"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - overlay
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=telegram

  adminer:
    image: adminer
    restart: always
    networks:
       - overlay
    ports:
      - "8080:8080"
